# Generated by Django 5.1.7 on 2025-03-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('company_name', models.CharField(max_length=1000)),
                ('position', models.CharField(max_length=1000)),
                ('mail', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=1000)),
                ('service_type', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=10000)),
            ],
        ),
    ]
